package locators;

public class AutomationLocators {
	/* css */public static final String TEMPLATE_PAGE_CONTENT = ".Polaris-Frame__Content";
	/* xpath */public static final String TEMPLATE_NAMES_COMMON = "//*[contains(@class,'spacingTight')]";
	/* xpath */public static final String EDIT_TEMPLATE = "//div[contains(text(),'Edit')]";
	/* xpath */public static final String DELETE_TEMPLATE = "//div[contains(text(),'Delete')]";
	/* xpath */public static final String CONFIRM = "//span[contains(@class,'Polaris-Button__Text')][contains(text(),'Confirm')]";
	/* xpath */public static final String UPDATE = "//*[contains(@class,'Polaris-Button__Text')][contains(text(),'Update')]";
	/* xpath */public static final String EDIT_TEMPLATE_NAME = "//button[contains(@class,'Button--iconOnly')]";
	/* xpath */public static final String EDITED_TEMPLATE_NAME_TEXTAREA = "//*[contains(@id,'PolarisTextField')]";
	/* xpath */public static final String TEMPLATE_EDIT_SUCCESS = "//div[contains(@class,'Polaris-Frame-Toast')]";
	/* css */public static final String EDIT_TEMPLATE_CATEGORY_DROPDOWN = ".Polaris-Select__Input";
	/* CSS */public static final String ENABLE_DISABLE_ICON = ".react-switch-handle";
	/* xpath */public static final String ENABLE_DISABLE_ICON_GENERIC = "//div[@class='react-switch-handle']/../input";
	/* xpath */public static final String TOGGLE_STATUS = "(//input[@role='switch'])";
	/* xpath */public static final String ERROR_POPUP = "//div[@class='Polaris-Frame-Toast']";
	/* xpath */public static final String TEMPLATES_DESC_COMMON = "//div[@class='Polaris-TextContainer']";
	/* xpath */public static final String PAGE_PLACEHOLDER1 = "//span[contains(text(),'You can send these manually from your WhatsApp too')]";
	/* xpath */public static final String PAGE_PLACEHOLDER2 = "//div[@class='Polaris-CalloutCard']";
	/* xpath */public static final String TEMPLATE_NAME_ERROR = "//div[@id='PolarisTextField1Error']";
	/* xpath */public static final String TEMPLATE_DESC_ERROR = "//div[@id='PolarisTextField2Error']";
	/* xpath */public static final String EDITED_TEMPLATE_NAME = "//input[@placeholder='Give a name to your template']";
	/* CSS */public static final String ABCART_ENABLE_DISABLE_ICON = "(//div[@class='react-switch-handle'])[1]";
	/* CSS */public static final String ODR_CRM_ENABLE_DISABLE_ICON = "(//div[@class='react-switch-handle'])[2]";
	/* CSS */public static final String ODR_SHIPMENT__ENABLE_DISABLE_ICON = "(//div[@class='react-switch-handle'])[3]";
	/* CSS */public static final String COD_ENABLE_DISABLE_ICON = "(//div[@class='react-switch-handle'])[4]";
	/* xpath */public static final String ABCART_ENABLE_CHECK = "(//input[@role='switch'])[1]";
	/* xpath */public static final String ORDER_CRM_ENABLE_CHECK = "(//input[@role='switch'])[2]";
	/* xpath */public static final String ORDER_SHIPMENT_ENABLE_CHECK = "(//input[@role='switch'])[3]";
	/* xpath */public static final String COD_ENABLE_CHECK = "(//input[@role='switch'])[4]";
	/* xpath */public static final String ACTION_SUCCESS_POPUP = "//div[@class='Polaris-Frame-Toast']";
	/* xpath */public static final String SETTINGS_DISABLED_GENERIC = "//button[contains(@class,'Polaris-Button--disabled')]";
	/* xpath */public static final String SETTINGS_GENERIC = "//div[contains(text(),'Settings')]";
	/* xpath */public static final String ENABLE_CHECK_GENERIC = "(//input[@role='switch'])";
	/* xpath */public static final String SAVE = "//span[contains(@class,'Polaris-Button__Text')][contains(text(),'Save')]";
	/* xpath */public static final String SPANISH_TEMPLATE_TXT = "//span[contains(text(),'Hola {{customer_name}}')]";
	/* xpath */public static final String PORTUGESE_ORDR_CRM_TEMPLATE = "//span[contains(text(),'Olá {{customer_name}}, obrigado por')]";
	/* xpath */public static final String COD_SPANISH_TEMPLATE = "//span[contains(text(),'Has click en el link para confirmar tu orden')]";
	/* xpath */public static final String ITALIAN_ORDER_SHIPMENT_TEMPLATE = "//span[contains(text(),'Ciao {{customer_name}}, il tuo ordine da {{shop_name}} è stato spedito ed è in arrivo. Rintraccia la tua spedizione utilizzando questo link {{tracking_ID}} {{tracking_url}}')]";
	/* xpath */public static final String TEMPLATE_LANGUAGE_SELECT = "//span[@class='Polaris-Choice__Label']";
	/* xpath */public static final String DISCOUNT_VALUE = "//input[@name='discount_percentage']";
	/* xpath */public static final String COUPON_CODE = "//input[@name='coupon_code']";
	/* xpath */public static final String PERCENTAGE_RADIO = "(//span[contains(@class,'Polaris-RadioButton__Backdrop')])[13]";
	/* xpath */public static final String FIXED_DISCOUNT__RADIO = "(//span[contains(@class,'Polaris-RadioButton__Backdrop')])[14]";
	/* xpath */ public static final String TRACKING_URL_FROM_ORDER_DATA = "//input[@id='tracking1']";
	/* xpath */public static final String TRACKING_FROM_ORDER_DATA_SELECT = "(//span[@class='Polaris-RadioButton__Backdrop'])[1]";
	/* xpath */public static final String THANK_YOU_PAGE = "//input[@id='tracking2']";
	/* xpath */public static final String THANK_YOU_PAGE_SELECT = "(//span[@class='Polaris-RadioButton__Backdrop'])[2]";
	/* id */public static final String CALL_COUNTRY_CODE_FIELD = "//select[@class='Polaris-Select__Input']";
	/* xpath */public static final String CALL_PHONE_FIELD = "//input[@placeholder='Example: 9035026993']";
	/* xpath */public static final String EMAIL_FIELD = "//input[@type='email']";
	/* xpath */public static final String INVALID_COUNTRY_CODE_ERROR_TEXT = "//div[contains(text(),'enter a valid country code')]";
	/* xpath */public static final String INVALID_PHONE_NUMBER_ERROR_TEXT = "//div[contains(text(),'Enter a valid phone number')]";
	/* xpath */public static final String INVALID_EMAIL_ERROR_TEXT = "//div[contains(text(),'Enter a valid email address')]";
	/* xpath */public static final String PHONE_VALIDATION_POPUP_ON_SAVE = "//div[contains(text(),'enter a valid country code')]";
	/* xpath */public static final String EMAIL_VALIDATION_POPUP_ON_SAVE = "//div[contains(text(),'enter a valid country code')]";
	/* xpath */public static final String CALL_CHECKBOX_COD_SETTINGS = "(//input[@class='Polaris-Checkbox__Input'])[3]";
	/* xpath */public static final String EMAIL_CHECKBOX_COD_SETTINGS = "(//input[@class='Polaris-Checkbox__Input'])[4]";
	/* xpath */public static final String CALL_CHECKBOX_CLICKABLE = "(//*[@class='Polaris-Checkbox__Backdrop'])[3]";
	/* xpath */public static final String EMAIL_CHECKBOX_CLICKABLE = "(//*[@class='Polaris-Checkbox__Backdrop'])[4]";
	/* xpath */public static final String ORDER_CONFIRMATION_TAG_FIELD = "//label[contains(text(),'Order Confirmed tag')]/following::input[1]";
	/* xpath */public static final String ORDER_CANCELLATION_TAG_FIELD = "//label[contains(text(),'Order Cancelled tag')]/following::input[1]";
	/* xpath */public static final String ORDER_NO_RESPONSE_TAG_FIELD = "//label[contains(text(),'No Response tag')]/following::input[1]";
	/* xpath */public static final String MODAL_CLOSE_BTN = "//button[@class='Polaris-Modal-CloseButton']";
	/* xpath */public static final String PRICING_HYPERLINK = "//a[contains(text(),'pricing chart')]";
	/* xpath */public static final String ORDER_SHIPMENT_NOTE = "//span[text()=': Order Shipment template language is based on language set in Order Confirmation.']";
	/* xpath */public static final String COD_TEMPLATE_NOTE = "//span[text()=': If both COD Order Confirmation and regular Order Confirmation templates are enabled, then the regular Order Confirmation message will be sent after your customer confirms a COD order.']";
	/* xpath */public static final String CANCEL_BTN = "//span[contains(text(),'Cancel')]";
	/* xpath */public static final String TEMPLATE_NAME_TXTBOX = "//input[@placeholder='Give a name to your template']";
	/* xpath */public static final String TEMPLATE_DESC_TXTBOX = "//textarea[@placeholder='Enter your content here']";
	/* xpath */public static final String CATEGORY_DD = "//select[@class='Polaris-Select__Input']";
	/* xpath */public static final String SETTINGS_ABCART_TEMPLATE = "(//div[contains(text(),'Settings')])[1]";
	/* xpath */public static final String SETTINGS_ODR_CONFIRMATION_TEMPLATE = "(//div[contains(text(),'Settings')])[2]";
	/* xpath */public static final String SETTINGS_ODR_SHIPMENT_TEMPLATE = "(//div[contains(text(),'Settings')])[3]";
	/* xpath */public static final String SETTINGS_COD_TEMPLATE = "(//div[contains(text(),'Settings')])[4]";
	/* xpath */public static final String PAYMENTSUCCESSFUL_TOGGLE = "//h2[.='Payment Successful']/following::div[1]";
	/* xpath */public static final String PAYMENTSUCCESSFUL_SETTINGS = "//h2[.='Payment Successful']/following::button[1]";
	/* xpath */public static final String ORDERCANCELLATION_TOGGLE = "//h2[.='Order Cancellation']/following::div[1]";
	/* xpath */public static final String ORDERCANCELLATION_SETTINGS = "//h2[.='Order Cancellation']/following::button[1]";
	/* CSS */public static final String SETTINGSCLOSEICON = ".Polaris-Modal-CloseButton";
	/* xpath */public static final String TEMPLATES_TOAST_MSG = "//div[@class='Polaris-Frame-Toast']";
//	/* xpath */public static final String PAYMENTSUCCESSFULL = "(//h2[@class='Polaris-Heading'])[5]";
//	/* xpath */public static final String ORDERCANCELLATION = "(//h2[@class='Polaris-Heading'])[6]";
	/* xpath */public static final String PAYMENTSUCCESSFULL_PRICINGCHART_HYPERLINK = "//a[contains(text(),'pricing chart')]";
	/* xpath */public static final String ORDERCANCELLATION_PRICINGCHART__HYPERLINK = "//a[contains(text(),'pricing chart')]";
	/* xpath */public static final String PHONENUMBER_HYPERLINK = "//a[.='phone number']";
	/* xpath */public static final String BUSINESSNAME_HYPERLINK = "//a[.='business name']";
	/* xpath */public static final String WHATSAPPSUPPORT_HYPERLINK = "//a[.='WhatsApp support number']";
	/* xpath */public static final String SHOPIFYADMINDISCOUNTS_HYPERLINK = "//a[.='Shopify admin > Discounts']";
	/* CSS */public static final String SETTINGSPOPUP = ".Polaris-Modal__BodyWrapper";
	/* xpath */public static final String SPANISH_LANGUAGE = "//div[.='Spanish']";
	/* xpath */public static final String ENGLISH_LANGUAGE = "//span[.='English']";
	/* xpath */public static final String SAVE_BTN = "//button[.='Save']";
	/* xpath */public static final String SETTINGS_CANCEL_BTN = "//button[.='Cancel']";
	/* xpath */public static final String PAYMENTSUCCESSFULL_SPANISH_TXTMSG = "//span[contains(text(),'Hola *{{customerName}}*, el pago de tu pedido *{{o')]";
	/* xpath */public static final String PAYMENTSUCCESSFULL_ENGLISH_TXTMSG = "//span[contains(text(),'Hi *{{customer_name}}*, the payment for your order')]";
	/* xpath */public static final String DISCOUNT = "(//div[@class='discountTypeHelpTextFontSize'])[1]";
	/* XPATH */public static final String DISCOUNT_TXTBOX = "//h2[.='Discount']/../following::input[4]";
	/* xpath */public static final String DISCOUNT_ZEROERROR = "//div[@class='Polaris-InlineError'][contains(text(),'Discount Value cannot be 0')]";
	/* xpath */public static final String DISCOUNT_EMPTYERROR = "//div[@class='Polaris-InlineError'][contains(text(),'Discount Value cannot be empty')]";
	/* xpath */public static final String DISCOUNT_INCREASE = "//div[@class='Polaris-TextField__Spinner']/div[1]";
	/* xpath */public static final String DISCOUNT_DECREASE = "//div[@class='Polaris-TextField__Spinner']/div[2]";
	/* xpath */public static final String FIXEDDISCOUNT_EMPTYERROR = "//div[@class='Polaris-InlineError'][contains(text(),'Coupon code cannot be empty')]";
	/* xpath */public static final String FIXEDDISCOUNT_TXTBOX = "//h2[.='Discount']/../following::input[4]";
	/* xpath */public static final String FIXEDDISCOUNT = "(//div[@class='discountTypeHelpTextFontSize'])[2]";
	/* xpath */public static final String DISCOUNT_TXTMSG = "//h2[.='Payment Successful']/following::span[1]";
	/* xpath */public static final String FIXEDDISCOUNT_TXTMSG = "//span[contains(.,'Hi *{{customer_name}}*, the payment for your order *{{order_ID}}* of *{{order_va')]";
	/* CSS */public static final String SCROLLER = ".Polaris-Scrollable--vertical.Polaris-Scrollable--hasTopShadow";
	/* xpath */public static final String DISCOUNT_BOX = "//div[@class='Polaris-TextField Polaris-TextField--hasValue']";
	/* xpath */public static final String AUTOMATEDPROMOTIONAL_TAB = "//button[@id='Automated Promotional']";
	/* xpath */public static final String CROSSSELL = "(//h2[@class='Polaris-Heading'])[2]";
	/* xpath */public static final String CUSTOMERWINBACK = "(//h2[@class='Polaris-Heading'])[3]";
	/* xpath */public static final String FEEDBACK = "(//h2[@class='Polaris-Heading'])[4]";
	/* xpath */public static final String CROSSSELL_TOGGLE = "//h2[.='Cross Sell']/following::div[1]";
	/* xpath */public static final String CUSTOMERWINBACK_TOGGLE = "//h2[.='Winback']/following::div[1]";
	/* xpath */public static final String FEEDBACK_TOGGLE = "//h2[.='Feedback']/following::div[1]";
	/* xpath */public static final String AUTOMATEDPROMOTIONAL_SUBNOTE = "//div[@class='Polaris-Header-Title__SubTitle']";
	/* xpath */public static final String CROSSSELL_PRICINGCHART_HYPERLINK = "//a[contains(text(),'pricing chart')]";
	/* xpath */public static final String CUSTOMERWINBACK_PRICINGCHART_HYPERLINK = "//a[contains(text(),'pricing chart')]";
	/* xpath */public static final String FEEDBACK_PRICINGCHART_HYPERLINK = "//a[contains(text(),'pricing chart')]";
	/* xpath */public static final String CROSSSELL_SETTINGS = "//h2[.='Cross Sell']/following::button[1]";
	/* xpath */public static final String CUSTOMERWINBACK_SETTINGS = "//h2[.='Cross Sell']/following::button[2]";
	/* xpath */public static final String FEEDBACK_SETTINGS = "//h2[.='Cross Sell']/following::button[3]";
	/* xpath */public static final String WHATSAPPNOTE = "//div[@class='Polaris-Layout__Annotation']/div[contains(.,'WhatsApp MessageAutomated WhatsApp messages are sent from our official WhatsApp')]";
	/* xpath */public static final String DISCOUNTNOTE = "//div[@class='Polaris-Layout__Annotation']/div[.='DiscountYou can enable and select the discount type.']";
	/* xpath */public static final String INTERVALNOTE = "//div[@class='Polaris-Layout__Annotation']/div[contains(.,'IntervalSelect the number of days after which you want the template to get trigg')]";
	/* xpath */public static final String INTERVAL_NOTE = "//div[@class='Polaris-TextContainer'][contains(text(),'Maximum days can be 7 and minimum is 3 days.')]";
	/* xpath */public static final String INCLUDE_DISCOUNT = "//span[.='Include discount coupon']/../span[1]/span/input[1]";
	/* xpath */public static final String DISCOUNT_TXT_MSG = "//h2[.='Cross Sell']/following::div[5]";
	/* xpath */public static final String WINBACKDISCOUNTTXTMSG = "//h2[.='Winback']/following::div[5]";
	/* xpath */public static final String INTERVAL_DROPDOWN = "//select[@class='Polaris-Select__Input']";
	/* xpath */public static final String RATEOURAPP_NOTE = "//div[@class='Polaris-CalloutCard__Content']";
	/* xpath */public static final String RATEOURAPP = "//a[.='Rate our app']";
	/* xpath */public static final String VERIFYDISABLEMSG = "//p[contains(.,'Upgrade to the Ultimate Plan to send automated template messages via our WhatsAp')]";
	/* CSS */public static final String UPGRADEPLAN = ".Polaris-Button--outline";
	/* xpath */public static final String CONTACTUS_NOTE = "(//div[@class='Polaris-Banner__Content'])[1]";
	/* xpath */public static final String CREATECUSTOMTEMPLATESBTN = "(//span[text()='Create Templates'])[1]";
	/* CSS */public static final String TEMPLATESNAMEINPUT = "[name='templateName']";
	/* xpath */public static final String BODYINPUT = "(//div[contains(text(),'Body')])/following::textarea[1]";
	/* xpath */public static final String HEADERINPUT = "(//div[contains(text(),'Header')])/following::input[1]";
	/* CSS */public static final String HEADERINPUTERROR = "//div[contains(text(),'Header')]/../following::div[6]";
	/* xpath */public static final String FOOTERINPUT = "(//div[contains(text(),'Footer')])/following::input[1]";
	/* CSS */public static final String FOOTERINPUTERROR = "//div[contains(text(),'Footer')]/../following::div[6]";
	/* CSS */public static final String BODYINPUTERROR = "//div[contains(text(),'Body')]/../following::div[9]";
	/* XPATH */public static final String CATEGORYDROPDOWN = "//div[text()='Category*']/following::select[1]";
	/* XPATH */public static final String TYPEDROPDOWN = "//div[text()='Category*']/following::select[2]";
	/* CSS */public static final String LANGUAGEDROPDOWN = "//div[text()='Category*']/following::select[3]";
	/* CSS */public static final String CALLTOACTIONSRADIOBUTTON = "[for='callToActions']";
	/* xpath */public static final String SAMPLEMESSAGEINPUT = "//div[contains(text(),'Sample Variable')]/following::input[1]";
	/* xpath */public static final String CREATEBTN = "//span[*='Create']";
	/* xpath */public static final String DISCARDBTN = "//span[*='Discard']";
	/* CSS */public static final String QUESTIONMARKBTN = "[title='Guide']";
	/* XPATH */public static final String CALLTOACTIONSDROPDOWN = "//h3[text()='Call to actions ']/following::select[1]";
	/* CSS */public static final String CALLTOACTIONSBUTTONNAME = "[placeholder='Button Name']";
	/* CSS */public static final String SELECTURLTYPE = "#PolarisSelect5";
	/* CSS */public static final String CALLTOACTIONSBUTTONVALUEINPUT = "[placeholder='Button Value']";
	/* xpath */public static final String ERRORPOP = "(//div[@class='Polaris-Frame-Toast Polaris-Frame-Toast--error'])[1]";
	/* CSS */public static final String TEMPLATESNAMEINPUTERROR = ".Polaris-InlineError";
	/* xpath */public static final String CALLTOACTIONSDROPDOWNTYPE = "//h3[text()='Call to actions ']/following::select[2]";
	/* xpath */public static final String VIEWTEMPLATESBTN = "//span[contains(text(),'View Templates')]";
	/* xpath */public static final String DELETECONFIRMATIONBTN = "//span[contains(text(),'Confirm')]";
	/* xpath */public static final String STARTGUIDEBTN = "//button[contains(.,'Start Guide')]";
	/* CSS */public static final String GUIDE = "img[title='Guide']";
	/* XPATH */public static final String NEXTSTEPBTN = "//span[contains(text(),'Next')]";
	/* XPATH */public static final String GUIDECOMPLETEDBTN = "//span[contains(text(),'Guide Completed')]";
	/* XPATH */public static final String HEADERLABEL = "//div[contains(text(),'Header')]";
	/* XPATH */public static final String FOOTERLABEL = "//div[contains(text(),'Footer')]";
	/* XPATH */public static final String BUTTONSLABEL = "//div[contains(text(),'Buttons')]";
	/* XPATH */public static final String TEMPLATELABEL = "//div[contains(text(),'Template Name')]";
	/* XPATH */public static final String CATEGORYLABEL = "//div[contains(text(),'Category')]";
	/* XPATH */public static final String LANGUAGELABEL = "//div[contains(text(),'Language')]";
	/* XPATH */public static final String TYPELABEL = "//div[contains(text(),'Type')]";
	/* XPATH */public static final String BODYLABEL = "//div[contains(text(),'Body')]";
	/* XPATH */public static final String SAMPLEMESSAGELABEL = "//div[contains(text(),'Sample Variable')]";
	/* XPATH */public static final String WHATSAPPSUPPORTTOOL = "//div[contains(text(),'Whatsapp Support Tool')]/following::button[1]";
	/* XPATH */public static final String ADD_VARIABLE = "//span[text()='+ Add Variable']";
	/* XPATH */public static final String PHONE_NUMBER_VARIABLE = "//div[text()='Phone Number']";
	/* XPATH */public static final String CUSTOM_VARIABLE = "//div[text()='Custom variable']";
	/* XPATH */public static final String LAST_ORDERED_DATE_VARIABLE = "//div[text()='Last Ordered Date']";
	/* XPATH */public static final String NUMBER_OF_ORDER_VARIABLE = "//div[text()='Number Of Order']";
	/* XPATH */public static final String TOTAL_ORDER_VALUE_VARIABLE = "//div[text()='Total Order Value']";
	/* XPATH */public static final String ABANDANED_CART_VARIABLE = "//div[text()='Abandoned Cart Value']";
	/* XPATH */public static final String OPT_IN_STATUS = "//div[text()='Opt in Status']";
	/* XPATH */public static final String OPT_IN_DATE = "//div[text()='Opt in date']";
	/* XPATH */public static final String OPT_IN_SOURCE = "//div[text()='Opt in Source']";
	/* xpath */public static final String DELETE_FIRST_TEMPLATE = "(//div[contains(text(),'Delete')])";
	/* xpath */public static final String ERROR_TOAST = "//div[contains(@class,'Polaris-Frame-Toast')]";
	/* xpath */public static final String PAYMENTSUCCESSFUL_ENABLE_CHECK = "(//input[@role='switch'])[5]";

	/* xpath */public static final String SETUPENABLENOW_BTN = "//button[.='Enable Now']";
	/* xpath */public static final String AB_CART_TEMPLATE = "//h2[.='Abandoned Cart']/following::span[2]";
	/* xpath */public static final String TEMPLATES = "//span[.='Automation']";

	/* id */public static final String AUTOMATED_TEMPLATES_TAB = "AutomatedMeasurer";
	///* xpath */public static final String MESSAGINGTAB = "//span[normalize-space()='Messaging']";
	/* xpath */public static final String CREATE_TEMPLATES = "//*[contains(@class,'Polaris-Button__Text')][contains(text(),'Create new Template')]";
	/* XPATH */public static final String TEMPLATE_NAME_FIELD = "//label[text()='Name']/following::input[1]";
	/* XPATH */public static final String TEMPLATE_DESC_FIELD = "//label[text()='Message']/following::textarea[1]";
	/* XPATH */public static final String CATEGORY_DROPDOWN = "//label[text()='Select Category']/following::select[1]";
	/* XPATH */public static final String CATEGORY_QUICK_DROPDOWN = "//label[text()='Select Category']/following::select[2]";
	/* XPATH */public static final String DISCOUNTVALUE = "//label[text()='Select Category']/following::input[2]";
	/* xpath */public static final String SUBMIT = "//span[text()='Save']";

	/// * xpath */public static final String CUSTOMTEMPLATES_TAB =
	/// "//button[@id='custom-templates']";
	/* XPATH */public static final String FIRST_NAME_VARIABLE = "//div[contains(text(),'First Name')]";
	/* XPATH */public static final String LAST_NAME_VARIABLE = "//div[contains(text(),'Last Name')]";

	/* XPATH */public static final String QUICKREPLYDROPDOWN = "//label[text()='Select Category']/following::select[2]";
	/* XPATH */public static final String TEMPLATEDISCOUNTVALUE = "//label[contains(text(),'Discount value')]/following::input[1]";
	/* xpath */public static final String GO_BACK_BTN = "//button[@aria-label='Close']";
	/* CSS */public static final String TOASTCLOSE_ICON = ".Polaris-Frame-Toast__CloseButton .Polaris-Icon__Svg";

	/* xpath */public static final String EXTENSION_TEMPLATES = "(//button[@id='Message Templates'])[1]";

	/* xpath */public static final String DISCOUNT_TYPE = "(//span[@class='Polaris-Checkbox__Backdrop'])[1]";
	/* xpath */public static final String DISCOUNT_TYPE__CHECKBOX = "(//input[@class='Polaris-Checkbox__Input'])[1]";

	/* xpath */public static final String TEMPLATE_DISCARD_BTN = "//span[contains(text(),'Cancel')]";
	/* xpath */public static final String PHONE_FIELD = "//select[@class='Polaris-Select__Input']/following::div[9]";

	/* xpath */public static final String PAYMENTSUCCESSFULLUSERSETTINGSTEXT = "//h2[.='Payment Successful User Settings']";
	/* xpath */public static final String CUSTOMERWINBACKFIXEDDISCOUNT_RADIO = "//input[@id='static']";
	/* xpath */public static final String RUNCAMPAIGN_BTN = "(//span[contains(text(),'Run Campaign')])[1]";
	/* CSS */public static final String SUFFIX_VALUE_INPUT = "[name='suffix']";
	/* XPath */ public static final String USER_SETTINGS_LEARNMORE = "//a[contains(text(),'Learn More')]";
//	/* XPath */ public static final String USERCHECK_INPUT = "(//input[@class='Polaris-Checkbox__Input'])[2]";
	/* XPath */ public static final String USERCHECKBOX = "(//span[@class='Polaris-Checkbox'])[2]";
	/* XPath */public static final String CROSSSELL_ENABLE_CHECK = "(//input[@role='switch'])[1]";

	/* Xpath */ public static final String DROPDOWN_IMAGE = "[value='IMAGE']";
	/* Xpath */ public static final String CHOOSEFILE_BTN = "//span[text()='Choose File']";
	/* css */ public static final String CHOOSEFILE_INPUT = "#uploadSampleMediaFile";
	/* XPath */ public static final String FILETYPE_NOTE = "//div[@class='fileTypeNote']";
	/* XPath */ public static final String UPLOADED_FILE = "//div[@class='removeMediaFile']";

	/* xpath */public static final String PAYMENT_SUCCESSFUL_ENABLE_CHECK = "(//input[@role='switch'])[5]";
	/* xpath */ public static final String PAYMENT_SUCCESSFUL_ENABLE_DISABLE_ICON = "(//div[@class='react-switch-handle'])[5]";
	/* XPATH */public static final String ORDER_CANCELLATION_ENABLE_CHECK = "(//input[@role='switch'])[6]";
	/* xpath */ public static final String ORDER_CANCELLATION_ENABLE_DISABLE_ICON = "(//div[@class='react-switch-handle'])[6]";

	///* xpath */public static final String CUSTOMTEMPLATES_TAB = "(//span[.='Campaigns'])/following::span[2]";
	
	/* xpath */public static final String MESSAGINGTAB = "//span[contains(text(),'CRM Tool')]";
	
	/* xpath */public static final String CUSTOMTEMPLATES_TAB = "(//span[.='Templates'])";
	
	/* xpath */public static final String TEMPLATE_NAMES_QUICKREPLY = "//div[@id='messageTemplates']//div[@class='Polaris-Layout']//span[text()='Quick Reply']/preceding-sibling::h2";

	/* xpath */public static final String PAYMENTSUCCESSFULL = "(//h2[@class='Polaris-Heading'])[6]";
	/* xpath */public static final String ORDERCANCELLATION = "(//h2[@class='Polaris-Heading'])[7]";
	
	/* XPath */ public static final String USERCHECK_INPUT = "(//span[contains(@class,'Polaris-Checkbox__Backdrop')])[1]";
	
	public static final String PRICINGCHART_URL = "PricingPageURL";
	public static final String CONFIGURATION_URL = "AdminConfigurationHyperlinks";
	public static final String LANGUAGE_TEXT = "Hola *{{customerName}}*, el pago de tu pedido *{{order_ID}}* de *{{order_value}}* fue exitoso.";
	public static final String FIXEDDISCOUNT_TEXT = "Apply coupon code: *{{discountCode}}* on your next order {{discountUrl}";
	public static final String FIXEDCOUPON_TEXT = "TEN";
	public static final String DISCOUNT_VALUE0 = "0";
	public static final String DISCOUNT_VALUE99 = "99";
	public static final String DISCOUNT_VALUE101 = "101";
	public static final String AUTOMATEDPROMOTIONAL_SUBNOTE_TXT = "SuperLemon provides the ability to send automated messages to your customers. You can enable these messages based on various events from the following list:";
	public static final String WINBACKDISCOUNT_TXTMSG = "We miss you at {{storeUrl}}. Thank you for your Purchase {{order_id}} We are offering a discount of {{discountPercent}}% for a limited period of time! (coupon code: {{discountCode}}) {{discountUrl}}";
	public static final String CROSSSELFIXEDDISCOUNT_TXTMSG = "Hi {{customer_name}}! Thank you for your Purchase {{name}} We are offering a discount for a limited period of time! Simply apply coupon code {{discountCode}} at the time of checkout {{discountUrl}}";
	public static final String WINBACKFIXEDDISCOUNT_TXTMSG = "We miss you at {{storeUrl}}. Thank you for your Purchase {{order_id}} We are offering a discount for a limited period of time! Simply apply coupon code {{discountCode}} at the time of checkout {{discountUrl}}";
	public static String[] DROPDOWNVALUES = { "3 Days", "4 Days", "5 Days", "6 Days", "7 Days" };
	public static final String INTERVAL_VALUE = "5";
	public static final String INTERVAL_VALUE1 = "3";
	public static final String PROMOTIONAL_NOTE_TXT = "Have multiple agents? Get Delighchat customer support tool with the Private waba plan";
//	public static final String CONTACTUS_NOTE_TXT = "For any bug reports or support related queries, please contact our team (support@superlemon.shop)";
	public static final String RATEOURAPP_NOTE_TXT = "If our app has added value to your store, please give us your love and support by writing a review. Team SuperLemon thanks you for your kindness";
	public static final String VERIFYDISABLEMSGVALUE = "Upgrade to the Ultimate Plan to send automated template messages via our WhatsApp Business Account or make custom templates via your own private WhatsApp Business Account";
	public static final String URL = "https://qaautomationstore2.myshopify.com/admin/discounts";
	public static final String TEMPLATENAMEDUPLICATE = "Duplicate Template Name";
	public static final String TEMPLATENAMEVALUE = "campaigntemplate";
	public static final String INVALIDTEMPLATENAMEVALUE = "sale";
	public static final String TYPEDROPDOWNVALUE = "TEXT";
//	public static final String CATEGORYDROPDOWNVALUE = "TRANSACTIONAL";
	public static final String LANGUAGEDROPDOWNVALUE = "en";
	public static final String BODYVALUE = "we have great offer for you";
	public static final String HEADERVALUE = "Hello Dear";
	public static final String INVALIDVALUE = "great billion days startedgreat billion days startedgreat big";
	public static final String FOOTERVALUE = "Thanks and Regards";
	public static final String URLDROPDOWNVALUE = "URL";
	public static final String CALLTOACTIONSBUTTONNAMEVALUE = "CallAction12";
	public static final String CALLTOACTIONSBUTTONVALUE = "https://qa.gupshup.io/";
	public static final String SAMPLEMESSAGEVALUE = "we have great offer for you";
	public static final String SAMPLEMESSAGEERROR = "Body and sample message doesn't match";
	public static final String BUTTONNAMEERROR = "Button Name is Required";
	public static final String BUTTONVALUEERROR = "Button Value is Required";
	public static final String CALLTOACTIONSTYPEDROPDOWNVALUE = "STATIC";
	public static final String TEMPLATENAMEERROR = "Duplicate Template Name";
	public static final String LABELOPTIONALVALUE = "(optional)";
	public static final String MANDATORYVALUE = "*";
	public static final String BODYVARIABLEVALUE = "we have great offer for you {{1}}";
	public static final String SAMPLEMESSAGEVARIABLEVALUE = "we have great offer for you Automation";
	public static final String BODYVARIABLE_FIRST_VALUE = "hello dear";
	public static final String BODYVARIABLE_SECOND_VALUE = "please visit our store";
	public static final String BODYVARIABLE_THIRD_VALUE = "for new offer";
//	public static final String BODYVARIABLE_FOURTH_VALUE = "and optin date is ";
//	public static final String BODYVARIABLE_FIFTH_VALUE = "and optin status is";
	public static final String BODYVARIABLE_SIXTH_VALUE = "please visit our store  ";
	public static final String NEW_AB_CART_TEMPLATE_VALUE = "Hi {{Customer name}},\n" + "\n"
			+ "Looks like you left a few items in your cart for {{Cart Value}} from {{Store Name}} and the order is not processed yet.\n"
			+ "\n"
			+ "Please Click on the \"Complete Purchase\" Button below and confirm your order. Hurry! Since the items in your cart are fast selling, place your order before items are out of stock. {{Discount Text}}\n"
			+ "\n" + "Kindly reply on the same chat for any support-related queries.\n" + "\n"
			+ "Complete payment: {{OrderLink}}";
	public static final String OLD_AB_CART_TEMPLATE_VALUE = "Hi {{customer_name}}, the payment for your order of {{currency}} {{total}} from {{shop_name}} is still pending. Click on the link to complete the payment and confirm your order";
	public static final String SAMPLETEXT = "Test";
	public static final String DISCOUNTVALUES = "25";
	public static final String COUPONCODE = " WHATSAPP20";
	public static final String CALLTOACTIONSTYPEDYNAMICDROPDOWNVALUE = "DYNAMIC";

	public static final String TUTORIAL_TITLE = "Why you should use automated templates?";
	public static final String[] ALLDROPDOWNVALUES = { "Select Type", "Text", "Image", "Video", "Document" };
	public static final String TYPEIMAGEDROPDOWNVALUE = "IMAGE";
	public static final String TYPEVIDEODROPDOWNVALUE = "VIDEO";
	public static final String TYPEDOCUMENTDROPDOWNVALUE = "DOCUMENT";
	public static final String IMAGE_VALIDFILE = "Upload.png";
	public static final String VIDEO_VALIDFILE = "video-below-2mb.mp4";
	public static final String DOCUMENT_VALIDFILE = "FIREBASE.pdf";
	public static final String DOCUMENT_ZIP = "extension.zip";
	public static final String IMAGE_TIFF = "image-tiff-file.tif";
	public static final String VIDEO_MOV = "video.mov";
	public static final String DOCUMENT_WARNING = "Please upload document file of type .pdf with a maximum size of 2MB";
	public static final String IMAGE_WARNING = "Please upload image file of type .jpeg or .png with a maximum size of 2MB";
	public static final String VIDEO_WARNING = "Please upload video file of type .mp4 with a maximum size of 16MB";
	public static final String IMAGE_INVALIDFILE = "image-above2mb.jpg";
	public static final String VIDEO_INVALIDFILE = "mp4-above-20mb.mp4";
	public static final String DOCUMENT_INVALIDFILE = "ef1663en.pdf";
	public static final String IMAGE_TYPE = "Supported media type: .jpeg and .png with a maximum size of 2MB";
	public static final String VIDEO_TYPE = "Supported media type: .mp4 with a maximum size of 16MB";
	public static final String DOCUMENT_TYPE = "Supported media type: .pdf with a maximum size of 2MB";

	public static final String TEMPLATE_EDIT = "Template updated successfully";
	public static final String CATEGORYDROPDOWNVALUE = "MARKETING";
	public static final String CONTACTUS_NOTE_TXT = "For any bug reports or support related queries, please contact our team (support@superlemon.xyz)";
}
